Workbench
oposs/agrammon pull request #472
Opened 2021-06-09 19:36 UTC by ChHaeni

Rename and move input variables

2021-06-09 19:50 UTC, zaucker requested changes
Remove old inputs: dairy_cows, pigs, ...

2021-06-10 07:00 UTC, ChHaeni commented
> Remove old inputs replaced by animals from input file: dairy_cows, pigs, ...

The old input is required to pass test run-complex-model-with-filters.t

2021-06-10 07:20 UTC, zaucker commented
> > Remove old inputs replaced by animals from input file: dairy_cows, pigs, ...
> 
> The old input is required to pass test [run-complex-model-with-filters.t](https://github.com/oposs/agrammon/blob/e528077bd2f04d0c0c05292a05a733ec79668c2f/t/run-complex-model-with-filters.t)

Oh, I see. We might have to deal with that when adding input validation.

2021-06-10 07:20 UTC, zaucker approved these changes

2021-06-10 07:20 UTC, merged